### ISSUE TITLE
argon2 build failures on windows

### ISSUE THREAD

**Issue by igalic** [Brainsware/sealas#12]
argon2 seems to build fine on windows:

```

==> argon2_elixir
Microsoft (R) Program Maintenance Utility Version 14.11.25547.0
Copyright (C) Microsoft Corporation.  All rights reserved.
	erl -eval "io:format(\"~s~n\", [lists:concat([\"ERTS_INCLUDE_PATH=\", code:root_dir(), \"/erts-\", erlang:system_info(version), \"/include\"])])" -s init stop -noshell > Makefile.auto.win
	nmake /                   /F Makefile.win priv\argon2_nif.dll
Microsoft (R) Program Maintenance Utility Version 14.11.25547.0
Copyright (C) Microsoft Corporation.  All rights reserved.
'priv\argon2_nif.dll' is up-to-date
Compiling 3 files (.ex)
Generated argon2_elixir app
```

but then when it's being loaded it fails with the following error:

```
...07:26:38.773 [error] Process #PID<0.5627.0> raised an exception
** (RuntimeError) An error occurred when loading Argon2.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use bcrypt_elixir (version 0.12) or pbkdf2_elixir.
See the Comeonin wiki for more information.
    (argon2_elixir) lib/argon2/base.ex:16: Argon2.Base.init/0
    (kernel) code_server.erl:1347: anonymous fn/1 in :code_server.handle_on_load/5
07:26:38.773 [warn] The on_load function for module Elixir.Argon2.Base returned {%RuntimeError{message: "An error occurred when loading Argon2.\nMake sure you have a C compiler and Erlang 20 installed.\nIf you are not using Erlang 20, either upgrade to Erlang 20 or\nuse bcrypt_elixir (version 0.12) or pbkdf2_elixir.\nSee the Comeonin wiki for more information.\n"},
 [{Argon2.Base, :init, 0, [file: 'lib/argon2/base.ex', line: 16]},
  {:code_server, :"-handle_on_load/5-fun-0-", 1,
   [file: 'code_server.erl', line: 1347]}]}
  1) test registration register with an existing email (SealasSso.RegistrationControllerTest)
     test/sealas_sso/controllers/registration_controller_test.exs:20
     ** (UndefinedFunctionError) function Argon2.Base.hash_password/3 is undefined (module Argon2.Base is not available)
     code: |> User.create_test_changeset(@create_attrs)
     stacktrace:
       (argon2_elixir) Argon2.Base.hash_password("some password", <<243, 123, 130, 7, 67, 238, 196, 60, 221, 18, 6, 156, 0, 102, 142, 152>>, [])
       (sealas_sso) lib/sealas_sso/types/hashedpassword.ex:7: EctoHashedPassword.cast/1
       (ecto) lib/ecto/changeset.ex:509: Ecto.Changeset.cast_field/8
       (ecto) lib/ecto/changeset.ex:472: Ecto.Changeset.process_param/7
       (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/changeset.ex:449: Ecto.Changeset.cast/6
       test/sealas_sso/controllers/registration_controller_test.exs:22: (test)
```

**Comment by DKhalil** [comment]
Solved in: https://github.com/riverrun/argon2_elixir/issues/16
